sudo: false

language: python
python:
    - "2.7.13"
    - "3.6.0" # flake8 needs Python 3.3 or better
    - "pypy"

before_install:
    - pip install --upgrade pip setuptools

install:
    - ./tools/travis/setupscan.sh
    - pip install flake8

before_script:
    - flake8 . --count --statistics --exit-zero

script:
    - ./tools/travis/scancode.sh
    - flake8 . --count --select=E999  # E999 SyntaxError: invalid syntax
